### ISSUE TITLE
to discuss: lodash rausschmeißen

### ISSUE THREAD

**Issue by charite-studium-und-lehre** [charite-studium-und-lehre/feedbacktool-levelup-frontend#1]
### Update 7.1.2019 von Nika, genauere Erklärung: 

die lodash-Bibliothek ist früher sehr beliebt gewesen. als javascript noch nicht so mächtig war, hat lodash das programmieren sehr viel bequemer gemacht.

mittlerweile hat es6 aber sehr viel funktionalität, die lodash überflüssig macht. (siehe z.B. hier: https://www.sitepoint.com/lodash-features-replace-es6/ aber auch in vielen anderen quellen im netz)

wir wollen möglichst auf alle externen bibliotheken verzichten, weil jede neue bibliothek auch in der config gepflegt werden muss, geupdated werden muss und so weiter. darum soll lodash aus levelUp raus. 

### Ursprünglicher Ticket-Text

lodash wird mindestens in EPAs/Data.js verwendet. Seit ES6 ist lodash nicht mehr notwendig. Wir wollen natürlich keine Bibliotheken im Build haben, die einfach nur unnötig Speicher verbrauchen. Darum:

- [ ] alle lodash-Einträge aus package.json löschen
- [ ] alle ehemaligen Verwendungen von lodash im Code fixen

**Comment by nikadomanska** [comment]
In Tickets #2510  und #2565 in Open Proejct abgebildet. Siehe dort zum Stand der Bearbeitung.
