### ISSUE TITLE
to discuss: Routing korrigieren - betrifft deployment auf verschiedenen stages

### ISSUE THREAD

**Issue by charite-studium-und-lehre** [charite-studium-und-lehre/feedbacktool-levelup-frontend#2]
### Beschreibung

1. bitte anschauen, wie in react routing umgesetzt wird (tutorial)
2. vergleich wie routing bei LevelUp umgesetzt ist
3. architektur skizze
4. Rücksprache mit Nika bzgl. umsetzung
5. Bitte den Link zu app-develop so korrigieren, dass es zu app-develop führt und nicht zum app

Antwort von Nika zum Punkt 5:

von mir aus muss das nicht korrigiert werden. es stimmt zwar, dass der redirect nicht vernünftig funktioniert, d.h. wenn wir (nicht die nutzer, die betrifft das gar nicht) auf app-develop gehen, einen datensatz wählen, und dann auch "Zu Dashboard gehen" klicken, dann landen wir nicht auf app-develop/dashboard sondern auf app/dashboard . aber:

es ist trotzdem ganz einfach, damit zu arbeiten. wenn der datensatz ausgewählt ist, dann gehen wir einfach nochmal in die adresszeile des browsers und korrigieren dort die adresse, sodass wir auf app-develop oder auf app-test1 oder wo auch immer wir hin wollen, landen.
das gute daran ist, so haben wir die echten anonymisierten testdaten auf allen stages (app-develop, test1, ...)  - und zwar ohne dass sich jetzt wieder ein entwickler ransetzt und irgendwelche routen korrigiert und dabei möglicherweise noch was kaputt macht.

**Comment by nikadomanska** [comment]
Idee auf unbestimmte Zeit verschoben.
