### ISSUE TITLE
to discuss: Farben und Barrierefreiheit

### ISSUE THREAD

**Issue by charite-studium-und-lehre** [charite-studium-und-lehre/feedbacktool-levelup-frontend#4]
Die Charité (und wahrscheinlich auch die anderen Projektpartner) soll einen möglichst Barrierefreien Zugang zu online-Angeboten ermöglichen. 

Die Farben sollten deswegen anpassbar sein, insbesondere sollte es einen "Hochkontrast"-Modus geben. Sowas in der Art gibts z.b. schon als Anzeigeeinstellung in IDEs, oder auch für Diagramme bei Datawrapper.de .

**Comment by nikadomanska** [comment]
Macht nur Sinn, wenn es eine Anforderung wird, die von außen  an das LevelUp Team herangetragen wird, direkt mit Farb-Spezifikation. Daher wird dieses Issue geschlossen.
