### ISSUE TITLE
Refactoring mit Kemal besprochen

### ISSUE THREAD

**Issue by charite-studium-und-lehre** [charite-studium-und-lehre/feedbacktool-levelup-frontend#5]
- react typography
- Styling vereinheitlichen, className-Attribut präferiert über style-Attribut
- props/state-variablen lieber spreaden , statt ständig this.props.prop123 oder this.state.state456 zu benutzen
- React braucht KEINE constructors
- onClick-Methoden als Arrow-Functions deklarieren (sonst erzeugt React bei jedem Update eine neue anonyme function)
- mal überlegen, ob clsx verwendet werden soll (library für conditional styling)
- stores refactoren 
- [ ]  Sprache der Variablen "schön", keine Abkürzung, nach Möglichkeit alles nur Englisch

**Comment by nikadomanska** [comment]
Einen Plan zum Refactoring haben wird jetzt in der Doku [doc/Architektur/Refactoring.md](https://github.com/charite-studium-und-lehre/feedbacktool-levelup-frontend/blob/develop/doc/Architektur/Refactoring.md) . Daher kann dieses Ticket hier geschlossen werden.
