### ISSUE TITLE
Refactoring Progress store

### ISSUE THREAD

**Issue by nikadomanska** [charite-studium-und-lehre/feedbacktool-levelup-frontend#7]
src/Progress/Store.js

Soll refactored werden im Hinblick auf 
1) Restrukturierung der store-Funktionalität nach Redux-Prinzipien, Extraktion von Types in eigene Datei; Transforms in Container (auch eigene Datei), sodass im store die puren action loads drinstehen
2) lodash rausschmeißen

In den commits bitte hinweisen, welchen der beiden Refactoring-Punkte der jeweilige commit betrifft.

**Comment by alex-at-charite** [comment]
closed with [this commit ](https://github.com/charite-studium-und-lehre/feedbacktool-levelup-frontend/commit/57c33f91c40ed5521b7ba898006c9c7963aedb58)
